server:
  port: 8989

management:
  port: 8990

info:
  component: Turbine

PREFIX:
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    root: WARN
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/

---
spring:
  profiles: docker
  rabbitmq:
      host: rabbitmq


#app:
#  rabbitmq:
#    host: rabbitmq

eureka:
  instance:
    hostname: turbine
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/